apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGdyaDBxZnk4
  CLOUDINARY_KEY: MzExNjk4ODE5MzgzOTg2
  CLOUDINARY_SECRET: bUF6Q0ZqWVV6TUNRVlJKWXJqZWo4cHhMdzNv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYzJoaGJtc3dNekEzSWl3aVlTSTZJbU50Ylc5Mk9UTTJOakJvT0hFeWNYTmtPSFowYTJacE1ITWlmUS5lNnNDaVgtb0FXYlZEam1GNnZ1Qkh3
  DB_URL: bW9uZ29kYitzcnY6Ly9zaGFzaGFuazpzaGFzaGFua0BjbHVzdGVyNy5sazBzZ3NpLm1vbmdvZGIubmV0Lz9hcHBOYW1lPWNsdXN0ZXI3
